## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: DinnerMeshDemo
  properties:
    services:
      - name: StorageService
        properties:
          description: StorageService description.
          osType: Windows
          codePackages:
            - name: StorageService
              image: storageservice:dev
              endpoints:
                - name: StorageServiceListener
                  port: 20003
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20003
                - name: DeliverService_URL
                  value: http://deliveryservice.dinnermeshdemo:20004/api/Delivery
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: DinnerMeshDemoNetwork