## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: DinnerMeshDemo
  properties:
    services:
      - name: DeliveryService
        properties:
          description: DeliveryService description.
          osType: Windows
          codePackages:
            - name: DeliveryService
              image: deliveryservice:dev
              endpoints:
                - name: DeliveryServiceListener
                  port: 20004
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20004
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              volumeRefs:
                - name: dinnerVolume
                  destinnationPath: C:\app\data
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: DinnerMeshDemoNetwork
          